/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#5d1900',
        'surface-container-highest': '#353534',
        'secondary-container': '#334d58',
        'on-tertiary-fixed-variant': '#832600',
        'on-error-container': '#ffdad6',
        'tertiary': '#ffb59d',
        'surface-container-lowest': '#0e0e0e',
        'error-container': '#93000a',
        'on-primary-container': '#f8f7ff',
        'inverse-surface': '#e5e2e1',
        'outline': '#8c90a1',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'error': '#ffb4ab',
        'on-secondary': '#19343e',
        'secondary-fixed-dim': '#afcbd8',
        'on-background': '#e5e2e1',
        'on-error': '#690005',
        'surface-dim': '#131313',
        'tertiary-fixed': '#ffdbd0',
        'on-secondary-container': '#a1bdca',
        'on-tertiary-fixed': '#390c00',
        'secondary': '#afcbd8',
        'tertiary-fixed-dim': '#ffb59d',
        'primary-fixed': '#dae1ff',
        'surface-bright': '#393939',
        'on-primary-fixed': '#001849',
        'inverse-primary': '#0054d6',
        'primary-container': '#0066ff',
        'surface-container-low': '#1c1b1b',
        'on-tertiary-container': '#fff6f4',
        'primary-fixed-dim': '#b3c5ff',
        'on-surface-variant': '#c2c6d8',
        'on-surface': '#e5e2e1',
        'background': '#131313',
        'primary': '#b3c5ff',
        'secondary-fixed': '#cbe7f5',
        'on-secondary-fixed': '#021f29',
        'on-primary': '#002b75',
        'inverse-on-surface': '#313030',
        'on-primary-fixed-variant': '#003fa4',
        'surface-tint': '#b3c5ff',
        'on-secondary-fixed-variant': '#304a55',
        'tertiary-container': '#cc4204',
        'surface-variant': '#353534',
        'outline-variant': '#424656',
        'surface': '#131313',
      },
      fontFamily: {
        'headline': ['Space Grotesk'],
        'body': ['Inter'],
        'label': ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
}
